spring.application.name=inventory-service


spring.datasource.url=jdbc:postgresql://localhost:1234/inventory
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=inventory_service